### ISSUE TITLE
[feat] - 버디 참여자 정보 제공

### ISSUE THREAD

**Issue by RedJunHee** [freediving-community/api-server#120]
버디모집글 내에서, 추후 확장 가능한 기능으로
1) 모집중 전체공개된 문의사항: [모두 조회. 로그인 후 글 작성]
2) 버디 모집 파티 구성원 전용대화: [모집장, 승인된 사용자만 조회/작성]
이렇게 생각을 하고 있는데요.

2번 기능을 생각해보면, 
클라이언트가 모집글 001을 클릭 
   버디서비스 요청=> 모집글 상세 내용 : 버디서비스에서 001 상세 정보 가져옴.
   커뮤서비스 요청=> 모집글 내 [문의사항 , 전용대화] 정보 가져옴. ( 이 때, 커뮤니티서비스=>버디서비스에게 001 모집글의 모집장 + 참가승인된 사용자 ID 가져오기 )
--------------------------------
ROWNUM / UserID / Role
 1            / 00001 / 모집장
 2            / 00023 / 참여자
 3            / 02080 / 참여자
--------------------------------
이런식으로 받을

**Comment by 0-ki** [comment]
채팅은 추후 확장 기능 고려하여, [버디매칭 / DM / 오픈채팅방] 3가지로 되도록 구성하려 합니다.
아래와 같이 채팅 생성 API를 호출해 주시는게 어떨까요?

1. 버디매칭에 모집 승인이 처리되는 시점에 (즉, 2명 이상의 사용자가 구성되는 시점에 채팅방을 생성), 커뮤니티 서비스로 {버디매칭ID, 모집장 유저ID, 참여자 유저ID}를 포함하여 채팅방 생성 API 호출
2. "채팅방 접속하기"의 기능은 해당 버디매칭 ID로 클라이언트가 직접 커뮤니티를 호출하면 되도록 구성
3. 버디매칭에 [추가 사용자 모집 승인이 될 때(1과 동일), 모집에서 사용자가 나갈 때, 모집이 삭제-폐기될 때] 3가지 경우에 커뮤니티 API 호출

=> 카프카로 위 내용이 전파된다면, 버디이벤트 서비스가 호출하는 것이 아닌 커뮤니티에서 구독하면서 처리하는 식으로 변경

=======================
+ 카톡 오픈채팅방 링크를 채팅에서 보여주기로 한 것 같은데, [오픈채팅방 입장하기]를 누르면 그 때 가서 버디 이벤트에 요청 보내는 것으로 할까요?
