### ISSUE TITLE
[docs] - Github Projects 사용 규칙 정하기

### ISSUE THREAD

**Issue by sasca37** [freediving-community/api-server#3]
# Github Projects 칸반보드 사용하기
- 이슈와 칸반보드를 활용해서 협업 하기
 
## 칸반보드 컬럼 설명 
- Todo : 새로 추가되는 모든 이슈 리스트들 
- In progress : 작업을 시작한 이슈들
- Done : 작업이 완료된 이슈들
   - PR 및 Merge가 완료되면 자동으로 Done으로 이동된다.

## 사용방법 및 규칙
- `Control` + `Space` 또는 하단 `Add Item` 버튼을 통해 이슈를 생성한다. 
- 이슈명은 브랜치 전략 (하단 참고)에 맞춰 `[브랜치명] - 작업명`으로 생성한다.
- 해당 작업 진행 시에 In progress로 이동(드래그) 시키고, `Label`, `Status`, `Priority`, `Size`, `일정` 등을 등록한다. 
- Draft 상태인 이슈는 Convert to Issue를 통해 이슈로 변경한다. 
- `(Optional)`  Milestone을 등록하고 싶은 경우 레포지토리 > Issues > Milestone에 신규 등록한 후 관련 이슈들을 생성하여 작업할 때 등록한다.
- 생성한 이슈를 토대로 브랜치를 생성하여 작업하여 PR 요청한다. 

### 브랜치 전략
- feat: 새로운 기능 추가
- fix: 버그 수정
- docs: 문서 수정
- style: 코드 포맷 변경, 세미콜론 누락, 코드 변경 없음
- refactor: 프로덕션 코드 리팩터링
- test: 테스트 추가, 테스트 코드 리팩터링, 프로덕션 코드 변경 없음
- chore: 빌드 테스크 업데이트, 패키지 매니저 환경설정, 프로덕션 코드 변경 없음

### 추가 변경 사항 
- 2023.12.18 : PR 요청 시 이슈 생성 안되도록 변경

**Comment by RedJunHee** [comment]
@sasca37 혹시 스웨거 문서관련 어노테이션이나 주석추가 등등은 브랜치 전략을 어떤걸로 설정하면 좋을까요?

**Comment by sasca37** [comment]
> [@sasca37](https://github.com/sasca37) 혹시 스웨거 문서관련 어노테이션이나 주석추가 등등은 브랜치 전략을 어떤걸로 설정하면 좋을까요?

코드 단이지만 문서화에 속한다고 판단이 돼서 docs 브랜치로 해보는것도 괜찮을 것 같습니다!
